name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.6
  vtable: ^0.4.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/background.png
    - images/background2.png
    - images/logo.png
    - images/lock.png
    - images/done.png
    - images/profile.jpg
